// 8088 CPU test bench -- data-driven instruction tests.
//
// The CPU is real -- full pin-level, CLK-driven, threaded.
// The 8284A clock generator is real -- drives OSC/CLK/PCLK/RESET/READY.
// The 8288 bus controller is real -- decodes S0-S2 into control signals.
// The 74S245 transceivers are real -- U8 (AD<->D), U12 (D<->MD for DRAM).
// The 74S373 address latches are real -- ALE-triggered address capture (U7/U9/U10).
// The 74S138 I/O decoder is real -- U66 decodes XA5-7 into PIC/PIT/PPI/DMA chip selects.
// The 74S20 NAND gate is real -- U64 generates ~ROM_ADDR_SEL from A16-A19.
// The 74S138 ROM decoder is real -- U46 decodes A13-A15 into ROM chip selects.
// The IC_ROM_8K is real -- U33 serves FE000-FFFFF from the BIOS binary.
// The 8259A PIC is real -- signal-level interrupt handling.
// BusGlue is a reactive Component: memory + generic I/O, subscribes to CLK.
//
// Each test is a flat binary assembled by NASM, loaded at 0100:0100
// (physical 0x01100) in DRAM. DS=SS=0 after reset. Results checked at 0x0500+.

#include "core/signal.h"
#include "core/callback_component.h"
#include "core/fiber_component.h"
#include "core/scheduler.h"
#include "board/socket.h"
#include "ic/ic_8088.h"
#include "ic/ic_8288.h"
#include "ic/ic_74s245.h"
#include "ic/ic_8259a.h"
#include "ic/ic_8284a.h"
#include "ic/ic_74s373.h"
#include "ic/ic_74s138.h"
#include "ic/ic_74s20.h"
#include "ic/ic_rom_8k.h"
#include "ic/ic_dram_256k.h"
#include "ic/ic_74s158.h"
#include "ic/ic_74s00.h"
#include "ic/ic_74s00_u81.h"
#include "ic/ic_74s08.h"
// ic_td1.h no longer needed -- TD1 is virtual inside U81
#include <spdlog/spdlog.h>
#include <cassert>
#include <cstring>
#include <fstream>
#include <vector>
#include <string>
#include <thread>
#include <chrono>

using namespace bench;

// Throwaway: no-op fiber for measuring fiber dispatch overhead.
class NoopFiber : public FiberComponent {
public:
    NoopFiber() : FiberComponent("noop") {}
protected:
    void run() override {
        for (;;) yield();
    }
    void on_power_on() override {}
    void on_power_off() override {}
    void on_signal_change(Fiber) override {}
};

// =========================================================================
// BusGlue: reactive Component -- address decode + memory.
// Subscribes to CLK, detects edges, drives data/control for each T-state.
// Handles memory and generic I/O. PIC chip-select comes from U66 (74S138).
// =========================================================================
class BusGlue : public CallbackComponent {
public:
    BusGlue() : CallbackComponent("BusGlue") { set_description("Bus Glue"); }

    Pin xa[20];                  // XA0-XA19 -- latched address from 74S373s
    Pin d[8];                    // D0-D7 -- system data bus
    Pin pin_s0, pin_s1, pin_s2;
    std::unique_ptr<uint8_t[]> io  = std::make_unique<uint8_t[]>(1 << 16);

    // DRAM ~WE pin -- BusGlue drives only ~WE.
    // Data transfer D<->MD is handled by U12 (74S245).
    // RAS/CAS/ADDR_SEL are generated by U81 from ~MEMR/~MEMW.
    Pin dram_we;                 // ~WE (active low)

    Signal* pic_ir[8] = {};       // IR0-IR7 (for test trigger port 0xF0)

    void init(Signal* xa_sigs[], Signal* d_sigs[], Signal& s0, Signal& s1, Signal& s2, Signal& clk) {
        for (int i = 0; i < 20; ++i) xa[i] = xa_sigs[i]->pin();
        for (int i = 0; i < 8; ++i)  d[i]  = d_sigs[i]->pin();
        pin_s0 = s0.pin();
        pin_s1 = s1.pin();
        pin_s2 = s2.pin();
        clk.connect(this);

        // Pin directions for wiring visualization.
        for (int i = 0; i < 20; ++i) declare_input(xa[i]);
        for (int i = 0; i < 8; ++i) { declare_input(d[i]); declare_output(d[i]); }
        declare_async_input(pin_s0); declare_async_input(pin_s1); declare_async_input(pin_s2);
        declare_input(clk.pin());

        // D pins are bidirectional: read cycles drive D (output), write cycles read D (input).
        declare_bidir_block({d[0], d[1], d[2], d[3], d[4], d[5], d[6], d[7]},
                            [this]() { return is_read_cycle() ? BidirDir::Output : BidirDir::Input; });
    }

    void connect_dram_we(Signal& we) {
        dram_we = we.pin();
        declare_output(dram_we);
    }

    // T-state machine
    enum class TState { IDLE, T1, T2, T3, T4 };
    TState t_state = TState::IDLE;
    uint8_t cycle_type = 7;
    uint32_t cycle_addr = 0;
    int bus_cycle_count = 0;
    bool dram_cycle = false;

    void reset() {
        t_state = TState::IDLE;
        cycle_type = 7;
        cycle_addr = 0;
        bus_cycle_count = 0;
        dram_cycle = false;
    }

protected:
    void on_signal_change(Fiber caller) override {
        on_clk_rising();
        on_clk_falling();
    }

private:
    uint8_t decode_status() {
        uint8_t v2 = (pin_s2.level() == Level::High) ? 1 : 0;
        uint8_t v1 = (pin_s1.level() == Level::High) ? 1 : 0;
        uint8_t v0 = (pin_s0.level() == Level::High) ? 1 : 0;
        return (v2 << 2) | (v1 << 1) | v0;
    }

    uint32_t read_address() {
        uint32_t addr = 0;
        for (int i = 0; i < 20; ++i)
            if (xa[i].level() == Level::High)
                addr |= (1u << i);
        return addr;
    }

    uint8_t read_d() {
        uint8_t val = 0;
        for (int i = 0; i < 8; ++i)
            if (d[i].level() == Level::High)
                val |= (1u << i);
        return val;
    }

    void drive_d(uint8_t val) {
        for (int i = 0; i < 8; ++i)
            d[i].drive((val >> i) & 1 ? Level::High : Level::Low);
    }

    void release_d() {
        for (int i = 0; i < 8; ++i)
            d[i].release();
    }

    bool is_read_cycle()  { return cycle_type == 0 || cycle_type == 1 || cycle_type == 4 || cycle_type == 5; }
    bool is_write_cycle() { return cycle_type == 2 || cycle_type == 6; }
    bool is_io_cycle()    { return cycle_type == 1 || cycle_type == 2; }
    bool is_inta_cycle()  { return cycle_type == 0; }
    // PIC ports 0x20-0x21 are handled by U66 (74S138) -> PIC ~CS. BusGlue skips them.
    bool is_hw_decoded(uint32_t addr) { return (addr & 0xFFFF) >= 0x20 && (addr & 0xFFFF) <= 0x3F; }
    // DRAM range: first 256KB (4 banks x 64KB).
    bool is_dram_range(uint32_t addr) { return addr < 0x40000; }

    // Drive ~WE for the DRAM cycle. RAS/CAS/ADDR_SEL are handled by
    // U81 (NAND) + TD1 (delay line) from ~MEMR/~MEMW automatically.
    void drive_dram_we() {
        dram_we.drive(is_write_cycle() ? Level::Low : Level::High);
    }

    void release_dram_we() {
        dram_we.drive(Level::High);
    }

    uint8_t io_read(uint16_t port) { return io[port]; }

    void io_write(uint16_t port, uint8_t val) {
        if (port == 0xF0) {
            // Test trigger port: drive IR lines High.
            // The 8284A's wait_quiescent after this CLK edge ensures the PIC
            // processes the rising edge before the next CLK tick.
            for (int i = 0; i < 8; i++) {
                if ((val & (1 << i)) && pic_ir[i])
                    pic_ir[i]->drive(Level::High);
            }
        } else if (port == 0xF1) {
            // Test clear port: drive IR lines Low.
            for (int i = 0; i < 8; i++) {
                if ((val & (1 << i)) && pic_ir[i])
                    pic_ir[i]->drive(Level::Low);
            }
        } else {
            io[port] = val;
        }
    }

    void on_clk_rising() {
        uint8_t status = decode_status();

        switch (t_state) {
        case TState::IDLE:
            if (status != 7) {
                t_state = TState::T1;
                cycle_type = status;
                cycle_addr = read_address();
                if (!is_io_cycle() && !is_inta_cycle()
                    && is_dram_range(cycle_addr & 0xFFFFF)) {
                    dram_cycle = true;
                    drive_dram_we();
                }
            }
            break;

        case TState::T1:
            t_state = TState::T2;
            break;

        case TState::T2:
            t_state = TState::T3;
            if (is_read_cycle()) {
                // DRAM reads: U12 (74S245) bridges MD->D automatically.
                // INTA: PIC drives D via ~CS from U66.
                // HW-decoded IO: handled by real ICs.
                if (!dram_cycle && !is_inta_cycle()
                    && is_io_cycle() && !is_hw_decoded(cycle_addr)) {
                    drive_d(io_read(cycle_addr & 0xFFFF));
                }
            } else if (is_write_cycle()) {
                // DRAM writes: U12 (74S245) bridges D->MD automatically.
                if (is_io_cycle() && !is_hw_decoded(cycle_addr)) {
                    io_write(cycle_addr & 0xFFFF, read_d());
                }
            }
            break;

        case TState::T3:
            t_state = TState::T4;
            if (dram_cycle)
                release_dram_we();
            break;

        case TState::T4:
            if (status != 7) {
                t_state = TState::T1;
                cycle_type = status;
                bus_cycle_count++;
                cycle_addr = read_address();
                if (!is_io_cycle() && !is_inta_cycle()
                    && is_dram_range(cycle_addr & 0xFFFFF)) {
                    dram_cycle = true;
                    drive_dram_we();
                } else {
                    dram_cycle = false;
                }
            } else {
                if (is_read_cycle()) {
                    release_d();
                }
                dram_cycle = false;
                bus_cycle_count++;
                t_state = TState::IDLE;
            }
            break;
        }
    }

    void on_clk_falling() {
        // DRAM write data transfer (D->MD) handled by U12 (74S245).
    }
};

// =========================================================================
// Test definition: binary file + expected memory values.
// =========================================================================
// 74S158 inverts both row and column address bits. Physical address and
// DRAM internal array offset differ because preload/readback bypass the
// pin interface. This maps physical -> internal for those paths.
static uint32_t dram_xlat(uint32_t phys) {
    uint8_t row = static_cast<uint8_t>(~(phys & 0xFF));
    uint8_t col = static_cast<uint8_t>(~((phys >> 8) & 0xFF));
    uint32_t bank = (phys >> 16) & 3;
    return (bank << 16) | (static_cast<uint32_t>(row) << 8) | col;
}

struct Expect { uint32_t addr; uint16_t value; const char* label; };

struct TestCase {
    const char* name;
    const char* bin_file;
    std::vector<Expect> expects;
};

static bool load_bin(const std::string& path, uint8_t* mem, uint32_t load_addr, uint32_t mem_size) {
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        spdlog::error("  cannot open {}", path);
        return false;
    }
    f.seekg(0, std::ios::end);
    auto size = f.tellg();
    f.seekg(0);
    if (load_addr + size > mem_size) {
        spdlog::error("  binary too large: {} bytes at 0x{:05X}", (int)size, load_addr);
        return false;
    }
    // Scatter-write through 74S158 address inversion so that pin-level
    // DRAM accesses (which see inverted row/col) find the correct data.
    std::vector<uint8_t> buf(static_cast<size_t>(size));
    f.read(reinterpret_cast<char*>(buf.data()), size);
    for (size_t i = 0; i < buf.size(); ++i)
        mem[dram_xlat(load_addr + static_cast<uint32_t>(i))] = buf[i];
    spdlog::debug("  loaded {} bytes at 0x{:05X} (translated)", (int)size, load_addr);
    return true;
}

int main() {
    spdlog::set_level(spdlog::level::info);
    spdlog::info("=== 8088 Test Bench ===");
    spdlog::info("ASM_TEST_DIR: {}", ASM_TEST_DIR);

    // Test table
    std::vector<TestCase> tests = {
        {"MOV/XCHG", "test_mov.bin", {
            {0x0500, 0x1234, "MOV imm16"},
            {0x0502, 0x5678, "MOV reg-reg"},
            {0x0504, 0x00AB, "MOV byte"},
            {0x0506, 0xDEF0, "XCHG ax"},
            {0x0508, 0x9ABC, "XCHG bx"},
        }},
#if 1
        {"ALU", "test_alu.bin", {
            {0x0500, 0x0042, "ADD"},
            {0x0502, 0x0010, "SUB"},
            {0x0504, 0xFFBE, "NEG"},
            {0x0506, 0x1234, "AND"},
            {0x0508, 0xFFFF, "OR"},
            {0x050A, 0xEDCB, "XOR"},
            {0x050C, 0xEDCA, "NOT"},
            {0x050E, 0x2468, "SHL"},
            {0x0510, 0x048D, "SHR"},
            {0x0512, 0x0001, "CMP/JE"},
            {0x0514, 0x008A, "ADC"},
            {0x0516, 0x00FE, "SBB"},
        }},
        {"CALL/RET", "test_call_ret.bin", {
            {0x0500, 0x0007, "near CALL/RET"},
            {0x0502, 0x1234, "PUSH/POP"},
            {0x0504, 0x000A, "nested CALL"},
            {0x0506, 0xBEEF, "PUSH/POP cross"},
        }},
        {"Jumps/Loops", "test_jumps.bin", {
            {0x0500, 0x0001, "JE"},
            {0x0502, 0x0001, "JNE"},
            {0x0504, 0x0001, "JL"},
            {0x0506, 0x0001, "JG"},
            {0x0508, 0x0001, "JB"},
            {0x050A, 0x0001, "JA"},
            {0x050C, 0x0005, "LOOP count"},
            {0x050E, 0x0037, "LOOP sum"},
        }},
        {"Interrupts", "test_int.bin", {
            {0x0500, 0xAA55, "INT 0x40"},
            {0x0502, 0x0001, "INT 3 (breakpoint)"},
            {0x0504, 0x0001, "INTO (OF=1)"},
            {0x0506, 0x0000, "INTO (OF=0, skip)"},
            {0x0508, 0x0001, "IRET restores IF"},
            {0x050A, 0x0003, "nested INT"},
        }},
        {"Strings", "test_string.bin", {
            {0x0500, 0x0001, "REP MOVSB"},
            {0x0502, 0x0001, "REP STOSB"},
            {0x0504, 0x0044, "LODSB"},
            {0x0506, 0x0001, "REPNE SCASB found"},
            {0x0508, 0x0001, "SCASB position"},
            {0x050A, 0x0001, "REPE CMPSB"},
            {0x050C, 0x0001, "MOVSW"},
            {0x050E, 0x0001, "STD reverse"},
        }},
        {"MUL/IMUL/Shifts", "test_mul.bin", {
            {0x0500, 0x0048, "MUL byte"},
            {0x0502, 0x0000, "MUL byte hi"},
            {0x0504, 0x4000, "MUL word lo"},
            {0x0506, 0x0000, "MUL word hi"},
            {0x0508, 0xFFC8, "IMUL byte"},
            {0x050A, 0x0100, "MUL overflow"},
            {0x050C, 0x00A0, "SHL AL,CL"},
            {0x050E, 0x0003, "SHR AX,CL"},
            {0x0510, 0xFFFE, "SAR AX,1"},
            {0x0512, 0x0030, "SHL AX,CL"},
        }},
        {"BCD/Exotic", "test_bcd.bin", {
            {0x0500, 0x0042, "DAA"},
            {0x0502, 0x0022, "DAS"},
            {0x0504, 0x0105, "AAA"},
            {0x0506, 0x0035, "AAD"},
            {0x0508, 0x0305, "AAM"},
            {0x050A, 0x00A0, "ROL"},
            {0x050C, 0x0028, "ROR"},
            {0x050E, 0x0001, "LAHF/SAHF"},
            {0x0510, 0x0055, "XLAT"},
            {0x0512, 0x0001, "STC/CLC/CMC"},
            {0x0514, 0x1234, "LEA"},
            {0x0516, 0x0001, "LDS"},
        }},
        {"FAR CALL", "test_farcall.bin", {
            {0x0500, 0x0001, "CALL FAR imm"},
            {0x0502, 0x0001, "RETF"},
            {0x0504, 0x0001, "CALL FAR indirect"},
            {0x0506, 0x0001, "RETF imm16"},
            {0x0508, 0x0001, "JMP FAR imm"},
            {0x050A, 0x2000, "CS after far call"},
        }},
        {"I/O (PIC ports)", "test_io.bin", {
            {0x0500, 0x00AB, "OUT imm8 / IN imm8 byte"},
            {0x0502, 0x00CD, "OUT DX / IN DX byte"},
            {0x0504, 0xBEEF, "OUT/IN word"},
            {0x0506, 0x00FE, "PIC IMR readback"},
            {0x0508, 0x0001, "Timer IRQ0 -> INT 8"},
            {0x050A, 0x0008, "INT 8 vector correct"},
            {0x050C, 0x0001, "EOI clears ISR"},
            {0x050E, 0x0001, "I/O doesn't touch memory"},
        }},
        {"DIV/IDIV", "test_div.bin", {
            {0x0500, 0x0003, "DIV byte quot"},
            {0x0502, 0x0001, "DIV byte rem"},
            {0x0504, 0x000A, "DIV word quot"},
            {0x0506, 0x0000, "DIV word rem"},
            {0x0508, 0xFFFD, "IDIV byte quot"},
            {0x050A, 0xFFFF, "IDIV byte rem"},
            {0x050C, 0x0001, "DIV by zero"},
            {0x050E, 0x0001, "DIV overflow"},
        }},
        { "DOS INT 21h", "test_dos.bin", {
            {0x0500, 0x0005, "AH=02 char count"},
            {0x0502, 0x0048, "AH=02 first char 'H'"},
            {0x0504, 0x006F, "AH=02 last char 'o'"},
            {0x0506, 0x000D, "AH=09 string length"},
            {0x0508, 0x0048, "AH=09 first char 'H'"},
            {0x050A, 0x0021, "AH=09 last char '!'"},
            {0x050C, 0x002A, "AH=4C exit code 42"},
        } },
#endif
        {"I/O (PIC ports)", "test_io.bin", {
            {0x0500, 0x00AB, "OUT imm8 / IN imm8 byte"},
            {0x0502, 0x00CD, "OUT DX / IN DX byte"},
            {0x0504, 0xBEEF, "OUT/IN word"},
            {0x0506, 0x00FE, "PIC IMR readback"},
            {0x0508, 0x0001, "Timer IRQ0 -> INT 8"},
            {0x050A, 0x0008, "INT 8 vector correct"},
            {0x050C, 0x0001, "EOI clears ISR"},
            {0x050E, 0x0001, "I/O doesn't touch memory"},
        }},
        {"IRQ (advanced)", "test_irq.bin", {
            {0x0500, 0x0001, "IRQ1 fires (INT 9)"},
            {0x0502, 0x0001, "Priority: IRQ0 first"},
            {0x0504, 0x0001, "Priority: IRQ1 second"},
            {0x0506, 0x0001, "Masked IRQ blocked"},
            {0x0508, 0x0001, "Specific EOI"},
            {0x050A, 0x0001, "Auto-EOI"},
            {0x050C, 0x0002, "Nested HW interrupts"},
        }},
        {"ROM (BIOS U33)", "test_rom.bin", {
            {0x0500, 0x0001, "ID string match"},
            {0x0502, 0x0031, "first ROM byte ('1')"},
            {0x0504, 0x0032, "last string byte ('2')"},
            {0x0506, 0xB000, "8K byte sum"},
        }},

    };

    // --- Wiring (permanent -- these are the copper traces on the test board) ---
    Signal vcc{"+5V"}, gnd{"GND"}, clk{"CLK"}, reset{"RESET"};
    Signal ready{"READY"}, nmi{"NMI"}, intr{"INTR"}, test_pin{"~TEST"};
    Signal cpu_lock{"~LOCK"}, rqgt0{"~RQ/GT0"};
    Signal qs0{"QS0"}, qs1{"QS1"}, s0{"~S0"}, s1{"~S1"}, s2{"~S2"};
    Bus ad{"AD", 8};
    Bus a_upper{"A", 12};

    // 8288 bus controller output signals
    Signal ale{"ALE"}, den{"~DEN"}, dtr{"DT/~R"};
    Signal memr{"~MEMR"}, memw{"~MEMW"};
    Signal ior_sig{"~IOR"}, iow_sig{"~IOW"}, inta_sig{"~INTA"};

    // U66 I/O decode outputs
    Signal dma_cs{"~DMA_CS"}, intr_cs{"~INTR_CS"}, pit_cs{"~PIT_CS"}, ppi_cs{"~PPI_CS"};
    Signal aen_bar{"~AEN"};  // No DMA in test bench, always High

    // System data bus (B side of 74S245 transceiver)
    Signal d0("D0"), d1("D1"), d2("D2"), d3("D3");
    Signal d4("D4"), d5("D5"), d6("D6"), d7("D7");
    Signal* d_arr[] = {&d0, &d1, &d2, &d3, &d4, &d5, &d6, &d7};

    // PIC A0 wired directly to latched address bit 0 (XA0) on real board.
    // ~CS comes from U66 ~Y1 (intr_cs) -- no manual BusGlue decode needed.

    // IRQ lines (BusGlue drives these via test trigger port 0xF0)
    Signal irq0{"IRQ0"}, irq1{"IRQ1"}, irq2{"IRQ2"}, irq3{"IRQ3"};
    Signal irq4{"IRQ4"}, irq5{"IRQ5"}, irq6{"IRQ6"}, irq7{"IRQ7"};
    Signal* irq_arr[] = {&irq0, &irq1, &irq2, &irq3, &irq4, &irq5, &irq6, &irq7};

    // DRAM signals
    Signal dram_ma0("MA0"), dram_ma1("MA1"), dram_ma2("MA2"), dram_ma3("MA3");
    Signal dram_ma4("MA4"), dram_ma5("MA5"), dram_ma6("MA6"), dram_ma7("MA7");
    Signal* dram_ma_arr[] = {&dram_ma0, &dram_ma1, &dram_ma2, &dram_ma3,
                             &dram_ma4, &dram_ma5, &dram_ma6, &dram_ma7};
    Signal ras("RAS");                 // U81 gate 2 output → TD1 input, U65 G1
    Signal cas("~CAS");               // U81 gate 3 output → U47 ~G2B
    Signal dram_we("~WE_DRAM");
    Signal addr_sel("ADDR_SEL");       // Delayed RAS, driven by U81's virtual TD1
    Signal md0("MD0"), md1("MD1"), md2("MD2"), md3("MD3");
    Signal md4("MD4"), md5("MD5"), md6("MD6"), md7("MD7");
    Signal mdp("MDP");
    Signal* md_arr[] = {&md0, &md1, &md2, &md3, &md4, &md5, &md6, &md7};

    // DRAM decode chain signals
    Signal ram_addr_sel("~RAM_ADDR_SEL");  // U48 output
    Signal refrsh_gate("~REFRSH_GATE");    // U81 gate 1 output
    // U65 bank select intermediates (BRD net names)
    Signal bank_sel_y4("N-000256"), bank_sel_y5("N-000251");
    Signal bank_sel_y6("N-000255"), bank_sel_y7("N-000252");
    // Per-bank RAS (U49 outputs → DRAM)
    Signal ras0("~RAS0"), ras1("~RAS1"), ras2("~RAS2"), ras3("~RAS3");
    Signal* ras_arr[] = {&ras0, &ras1, &ras2, &ras3};
    // Per-bank CAS (U47 outputs → DRAM)
    Signal dram_cas0("~CAS0"), dram_cas1("~CAS1"), dram_cas2("~CAS2"), dram_cas3("~CAS3");
    Signal* dram_cas_arr[] = {&dram_cas0, &dram_cas1, &dram_cas2, &dram_cas3};

    // 8284A signals
    Signal osc{"OSC"}, pclk{"PCLK"}, res{"RES"};

    // Latched address bus (outputs from 74S373 latches, active after ALE)
    Signal xa[20] = {
        Signal("XA0"),  Signal("XA1"),  Signal("XA2"),  Signal("XA3"),
        Signal("XA4"),  Signal("XA5"),  Signal("XA6"),  Signal("XA7"),
        Signal("XA8"),  Signal("XA9"),  Signal("XA10"), Signal("XA11"),
        Signal("XA12"), Signal("XA13"), Signal("XA14"), Signal("XA15"),
        Signal("XA16"), Signal("XA17"), Signal("XA18"), Signal("XA19"),
    };

    // All traces on this test board. On power loss, every trace discharges.
    std::vector<Signal*> all_traces = {
        &vcc, &clk, &reset, &ready, &nmi, &intr, &test_pin,
        &cpu_lock, &rqgt0, &qs0, &qs1, &s0, &s1, &s2,
        &ale, &den, &dtr, &memr, &memw, &ior_sig, &iow_sig, &inta_sig,
        &dma_cs, &intr_cs, &pit_cs, &ppi_cs, &aen_bar,
        &osc, &pclk, &res,
    };
    for (int i = 0; i < 8; ++i)  all_traces.push_back(&ad[i]);
    for (int i = 0; i < 12; ++i) all_traces.push_back(&a_upper[i]);
    for (int i = 0; i < 8; ++i)  all_traces.push_back(d_arr[i]);
    for (int i = 0; i < 8; ++i)  all_traces.push_back(irq_arr[i]);
    for (int i = 0; i < 20; ++i) all_traces.push_back(&xa[i]);
    for (int i = 0; i < 8; ++i)  all_traces.push_back(dram_ma_arr[i]);
    for (int i = 0; i < 8; ++i)  all_traces.push_back(md_arr[i]);
    all_traces.push_back(&mdp);
    all_traces.push_back(&ras);
    all_traces.push_back(&cas);
    for (int i = 0; i < 4; ++i)  all_traces.push_back(ras_arr[i]);
    for (int i = 0; i < 4; ++i)  all_traces.push_back(dram_cas_arr[i]);
    all_traces.push_back(&dram_we);
    all_traces.push_back(&addr_sel);
    all_traces.push_back(&ram_addr_sel);
    all_traces.push_back(&refrsh_gate);
    all_traces.push_back(&bank_sel_y4); all_traces.push_back(&bank_sel_y5);
    all_traces.push_back(&bank_sel_y6); all_traces.push_back(&bank_sel_y7);
    // td1_out8/td1_out12 removed -- TD1 is virtual inside U81

    // U11: 8284A Clock Generator
    Socket clk_socket{"U11", "8284A", 18};
    clk_socket.wire(2, pclk);    // PCLK output
    clk_socket.wire(5, ready);   // READY output
    clk_socket.wire(8, clk);     // CLK output
    clk_socket.wire(9, gnd);     // GND
    clk_socket.wire(10, reset);  // RESET output
    clk_socket.wire(11, res);    // RES input (PWR_GOOD)
    clk_socket.wire(12, osc);    // OSC output
    clk_socket.wire(18, vcc);    // VCC
    auto* clk_gen = clk_socket.emplace<IC_8284A>();
    clk_gen->psu_wire(vcc.pin(), gnd.pin(), res.pin(), nmi.pin(),
                      s0.pin(), s1.pin(), s2.pin(), aen_bar.pin());

    // U3: 8088 CPU
    Socket cpu_socket{"U3", "8088", 40};
    cpu_socket.wire(1, gnd); cpu_socket.wire(20, gnd);
    cpu_socket.wire(31, vcc); cpu_socket.wire(40, vcc);
    for (int i = 0; i < 8; ++i) cpu_socket.wire(16 - i, ad[i]);
    for (int i = 0; i < 7; ++i) cpu_socket.wire(8 - i, a_upper[i]);
    for (int i = 0; i < 5; ++i) cpu_socket.wire(39 - i, a_upper[7 + i]);
    cpu_socket.wire(19, clk); cpu_socket.wire(21, reset);
    cpu_socket.wire(22, ready); cpu_socket.wire(17, nmi);
    cpu_socket.wire(18, intr); cpu_socket.wire(23, test_pin);
    cpu_socket.wire(29, cpu_lock); cpu_socket.wire(30, rqgt0);
    cpu_socket.wire(24, qs1); cpu_socket.wire(25, qs0);
    cpu_socket.wire(26, s0); cpu_socket.wire(27, s1); cpu_socket.wire(28, s2);
    auto* cpu = cpu_socket.emplace<IC_8088>(0x0100, 0x0100);

    // U6: 8288 Bus Controller
    Socket bc_socket{"U6", "8288", 20};
    bc_socket.wire(1, gnd);
    bc_socket.wire(2, clk);
    bc_socket.wire(3, s1);
    bc_socket.wire(4, den);
    bc_socket.wire(5, ale);
    bc_socket.wire(6, vcc);    // CEN = always enabled
    bc_socket.wire(7, memr);
    bc_socket.wire(8, memw);
    bc_socket.wire(12, iow_sig);
    bc_socket.wire(13, ior_sig);
    bc_socket.wire(14, inta_sig);
    bc_socket.wire(15, vcc);   // ~AEN = High (no DMA)
    bc_socket.wire(16, dtr);
    bc_socket.wire(18, s2);
    bc_socket.wire(19, s0);
    bc_socket.wire(20, vcc);
    auto* bc = bc_socket.emplace<IC_8288>();

    // U8: 74S245 Data Bus Transceiver
    Socket xcvr_socket{"U8", "74S245", 20};
    xcvr_socket.wire(1, den);
    xcvr_socket.wire(2, ad[7]); xcvr_socket.wire(3, ad[6]);
    xcvr_socket.wire(4, ad[5]); xcvr_socket.wire(5, ad[4]);
    xcvr_socket.wire(6, ad[3]); xcvr_socket.wire(7, ad[2]);
    xcvr_socket.wire(8, ad[1]); xcvr_socket.wire(9, ad[0]);
    xcvr_socket.wire(10, gnd);
    xcvr_socket.wire(11, d0); xcvr_socket.wire(12, d1);
    xcvr_socket.wire(13, d2); xcvr_socket.wire(14, d3);
    xcvr_socket.wire(15, d4); xcvr_socket.wire(16, d5);
    xcvr_socket.wire(17, d6); xcvr_socket.wire(18, d7);
    xcvr_socket.wire(19, dtr);
    xcvr_socket.wire(20, vcc);
    auto* xcvr = xcvr_socket.emplace<IC_74S245>();

    // U12: 74S245 Memory Data Bus Transceiver
    // Bridges D0-D7 (system data bus) to MD0-MD7 (DRAM data bus).
    // DIR = ~XMEMR (~MEMR, since U14 not implemented): Low=B->A (MD->D, reads), High=A->B (D->MD, writes)
    // ~OE = ~RAM_ADDR_SEL: enabled when address is in RAM range.
    Socket mem_xcvr_socket{"U12", "74S245", 20};
    mem_xcvr_socket.wire(1, ram_addr_sel);   // ~G = ~RAM_ADDR_SEL
    mem_xcvr_socket.wire(2, d0);             // A1 = D0
    mem_xcvr_socket.wire(3, d1);             // A2 = D1
    mem_xcvr_socket.wire(4, d2);             // A3 = D2
    mem_xcvr_socket.wire(5, d3);             // A4 = D3
    mem_xcvr_socket.wire(6, d4);             // A5 = D4
    mem_xcvr_socket.wire(7, d5);             // A6 = D5
    mem_xcvr_socket.wire(8, d6);             // A7 = D6
    mem_xcvr_socket.wire(9, d7);             // A8 = D7
    mem_xcvr_socket.wire(10, gnd);
    mem_xcvr_socket.wire(11, md7);           // B8 = MD7
    mem_xcvr_socket.wire(12, md6);           // B7 = MD6
    mem_xcvr_socket.wire(13, md5);           // B6 = MD5
    mem_xcvr_socket.wire(14, md4);           // B5 = MD4
    mem_xcvr_socket.wire(15, md3);           // B4 = MD3
    mem_xcvr_socket.wire(16, md2);           // B3 = MD2
    mem_xcvr_socket.wire(17, md1);           // B2 = MD1
    mem_xcvr_socket.wire(18, md0);           // B1 = MD0
    mem_xcvr_socket.wire(19, memr);          // DIR = ~XMEMR (~MEMR)
    mem_xcvr_socket.wire(20, vcc);
    auto* mem_xcvr = mem_xcvr_socket.emplace<IC_74S245>();

    // U10: 74S373 Address Latch (low byte: AD0-AD7 -> XA0-XA7)
    Socket latch_lo{"U10", "74S373", 20};
    latch_lo.wire(1, gnd);       // ~OE = always enabled
    latch_lo.wire(11, ale);      // LE = ALE
    latch_lo.wire(10, gnd);
    latch_lo.wire(20, vcc);
    // D inputs = AD0-AD7, Q outputs = XA0-XA7
    // D pins: 3,4,7,8,13,14,17,18  Q pins: 2,5,6,9,12,15,16,19
    latch_lo.wire(3, ad[0]); latch_lo.wire(2, xa[0]);
    latch_lo.wire(4, ad[1]); latch_lo.wire(5, xa[1]);
    latch_lo.wire(7, ad[2]); latch_lo.wire(6, xa[2]);
    latch_lo.wire(8, ad[3]); latch_lo.wire(9, xa[3]);
    latch_lo.wire(13, ad[4]); latch_lo.wire(12, xa[4]);
    latch_lo.wire(14, ad[5]); latch_lo.wire(15, xa[5]);
    latch_lo.wire(17, ad[6]); latch_lo.wire(16, xa[6]);
    latch_lo.wire(18, ad[7]); latch_lo.wire(19, xa[7]);
    auto* latch_lo_ic = latch_lo.emplace<IC_74S373>();

    // U9: 74S373 Address Latch (mid byte: A0-A7 -> XA8-XA15)
    Socket latch_mid{"U9", "74S373", 20};
    latch_mid.wire(1, gnd);      // ~OE = always enabled
    latch_mid.wire(11, ale);     // LE = ALE
    latch_mid.wire(10, gnd);
    latch_mid.wire(20, vcc);
    latch_mid.wire(3, a_upper[0]); latch_mid.wire(2, xa[8]);
    latch_mid.wire(4, a_upper[1]); latch_mid.wire(5, xa[9]);
    latch_mid.wire(7, a_upper[2]); latch_mid.wire(6, xa[10]);
    latch_mid.wire(8, a_upper[3]); latch_mid.wire(9, xa[11]);
    latch_mid.wire(13, a_upper[4]); latch_mid.wire(12, xa[12]);
    latch_mid.wire(14, a_upper[5]); latch_mid.wire(15, xa[13]);
    latch_mid.wire(17, a_upper[6]); latch_mid.wire(16, xa[14]);
    latch_mid.wire(18, a_upper[7]); latch_mid.wire(19, xa[15]);
    auto* latch_mid_ic = latch_mid.emplace<IC_74S373>();

    // U7: 74S373 Address Latch (high nibble: A8-A11 -> XA16-XA19)
    Socket latch_hi{"U7", "74S373", 20};
    latch_hi.wire(1, gnd);       // ~OE = always enabled
    latch_hi.wire(11, ale);      // LE = ALE
    latch_hi.wire(10, gnd);
    latch_hi.wire(20, vcc);
    latch_hi.wire(3, a_upper[8]);  latch_hi.wire(2, xa[16]);
    latch_hi.wire(4, a_upper[9]);  latch_hi.wire(5, xa[17]);
    latch_hi.wire(7, a_upper[10]); latch_hi.wire(6, xa[18]);
    latch_hi.wire(8, a_upper[11]); latch_hi.wire(9, xa[19]);
    // D4-D7 unused on U7 -- only 4 address bits (A16-A19)
    auto* latch_hi_ic = latch_hi.emplace<IC_74S373>();

    // U66: 74S138 I/O Address Decoder
    // Decodes XA5-XA7 when XA8=0, XA9=0, ~AEN=High (no DMA).
    // ~Y0=~DMA_CS (0x00), ~Y1=~INTR_CS (0x20), ~Y2=~PIT_CS (0x40), ~Y3=~PPI_CS (0x60)
    Socket io_decode{"U66", "74S138", 16};
    io_decode.wire(1, xa[5]);       // A = XA5
    io_decode.wire(2, xa[6]);       // B = XA6
    io_decode.wire(3, xa[7]);       // C = XA7
    io_decode.wire(4, xa[9]);       // ~G2A = XA9 (must be Low)
    io_decode.wire(5, xa[8]);       // ~G2B = XA8 (must be Low)
    io_decode.wire(6, aen_bar);     // G1 = ~AEN (High = CPU on bus)
    io_decode.wire(8, gnd);
    io_decode.wire(15, dma_cs);     // ~Y0 = ~DMA_CS (0x00-0x1F)
    io_decode.wire(14, intr_cs);    // ~Y1 = ~INTR_CS (0x20-0x3F)
    io_decode.wire(13, pit_cs);     // ~Y2 = ~PIT_CS (0x40-0x5F)
    io_decode.wire(12, ppi_cs);     // ~Y3 = ~PPI_CS (0x60-0x7F)
    io_decode.wire(16, vcc);
    auto* io_dec = io_decode.emplace<IC_74S138>();

    // U2: 8259A PIC
    Socket pic_socket{"U2", "8259A", 28};
    pic_socket.wire(1, intr_cs);
    pic_socket.wire(2, iow_sig);
    pic_socket.wire(3, ior_sig);
    pic_socket.wire(4, d7);  pic_socket.wire(5, d6);
    pic_socket.wire(6, d5);  pic_socket.wire(7, d4);
    pic_socket.wire(8, d3);  pic_socket.wire(9, d2);
    pic_socket.wire(10, d1); pic_socket.wire(11, d0);
    pic_socket.wire(14, gnd);
    pic_socket.wire(16, vcc);         // ~SP/~EN = VCC (master mode)
    pic_socket.wire(17, intr);        // INT -> CPU INTR
    pic_socket.wire(18, irq0); pic_socket.wire(19, irq1);
    pic_socket.wire(20, irq2); pic_socket.wire(21, irq3);
    pic_socket.wire(22, irq4); pic_socket.wire(23, irq5);
    pic_socket.wire(24, irq6); pic_socket.wire(25, irq7);
    pic_socket.wire(26, inta_sig);
    pic_socket.wire(27, xa[0]);
    pic_socket.wire(28, vcc);
    auto* pic = pic_socket.emplace<IC_8259A>();

    // --- ROM decode chain ---

    // ROM-specific signals
    Signal rom_addr_sel{"~ROM_ADDR_SEL"};   // U64 output: active low when A19:A16 = 1111
    Signal cs7{"~CS7"};                      // U46 output: ROM chip select for U33 (FE000-FFFFF)

    // U64: 74S20 Dual 4-Input NAND (ROM address decode)
    // Gate 1: NAND(A19, A18, A17, A16) -> ~ROM_ADDR_SEL
    // Active low when all four high bits are set (address >= F0000).
    Socket nand_socket{"U64", "74S20", 14};
    nand_socket.wire(1, xa[19]);            // A1 = XA19
    nand_socket.wire(2, xa[18]);            // B1 = XA18
    nand_socket.wire(4, xa[17]);            // C1 = XA17
    nand_socket.wire(5, xa[16]);            // D1 = XA16
    nand_socket.wire(6, rom_addr_sel);      // Y1 = ~ROM_ADDR_SEL
    nand_socket.wire(7, gnd);
    nand_socket.wire(14, vcc);
    auto* nand_ic = nand_socket.emplace<IC_74S20>();

    // U46: 74S138 ROM Chip Select Decoder
    // Decodes A15:A13 into ~CS2-~CS7 when ~ROM_ADDR_SEL=Low and ~MEMR=Low.
    // G1 = VCC (always enabled -- on real board this is ~RESET_DRV,
    //           but 8288 doesn't issue ~MEMR during reset, so safe).
    Socket rom_decode{"U46", "74S138", 16};
    rom_decode.wire(1, xa[13]);             // A = XA13
    rom_decode.wire(2, xa[14]);             // B = XA14
    rom_decode.wire(3, xa[15]);             // C = XA15
    rom_decode.wire(4, memr);               // ~G2A = ~MEMR (active during memory read)
    rom_decode.wire(5, rom_addr_sel);       // ~G2B = ~ROM_ADDR_SEL
    rom_decode.wire(6, vcc);                // G1 = VCC (see note above)
    rom_decode.wire(7, cs7);                // ~Y7 = ~CS7 -> U33 (FE000-FFFFF)
    // ~Y0-~Y6 unconnected (no other ROM chips installed in test bench)
    rom_decode.wire(8, gnd);
    rom_decode.wire(16, vcc);
    auto* rom_dec = rom_decode.emplace<IC_74S138>();

    // U33: 8K x 8 BIOS ROM (FE000-FFFFF)
    // Address pins wired to XA0-XA12, data pins to system data bus (D0-D7).
    // On the real board, ROM data pins connect to XD0-XD7 which reach D0-D7
    // through U13/U14 system bus transceivers. We connect directly to D0-D7
    // since U13/U14 are not modeled yet (U12 is DRAM-only).
    std::string bios_path = std::string(ASSETS_DIR) + "/BIOS_IBM5150_27OCT82_1501476_U33.BIN";
    Socket rom_socket{"U33", "8K_X_8ROS", 24};
    rom_socket.wire(1, xa[7]);              // A7
    rom_socket.wire(2, xa[6]);              // A6
    rom_socket.wire(3, xa[5]);              // A5
    rom_socket.wire(4, xa[4]);              // A4
    rom_socket.wire(5, xa[3]);              // A3
    rom_socket.wire(6, xa[2]);              // A2
    rom_socket.wire(7, xa[1]);              // A1
    rom_socket.wire(8, xa[0]);              // A0
    rom_socket.wire(9, d0);                 // D0
    rom_socket.wire(10, d1);                // D1
    rom_socket.wire(11, d2);                // D2
    rom_socket.wire(12, gnd);               // GND
    rom_socket.wire(13, d3);                // D3
    rom_socket.wire(14, d4);                // D4
    rom_socket.wire(15, d5);                // D5
    rom_socket.wire(16, d6);                // D6
    rom_socket.wire(17, d7);                // D7
    rom_socket.wire(18, xa[11]);            // A11
    rom_socket.wire(19, xa[10]);            // A10
    rom_socket.wire(20, cs7);               // ~CS
    rom_socket.wire(21, xa[12]);            // A12
    rom_socket.wire(22, xa[9]);             // A9
    rom_socket.wire(23, xa[8]);             // A8
    rom_socket.wire(24, vcc);               // VCC
    auto* rom_ic = rom_socket.emplace<IC_ROM_8K>("BIOS_U33", bios_path);

    all_traces.push_back(&rom_addr_sel);
    all_traces.push_back(&cs7);

    // --- DRAM: 4 banks x 9 chips = 36 sockets (IC_DRAM_256K) ---
    auto make_dram_bank = [&](int start_u) -> std::vector<Socket> {
        std::vector<Socket> bank;
        bank.reserve(9);
        for (int i = 0; i < 9; ++i)
            bank.emplace_back("U" + std::to_string(start_u + i), "RAM_64K_X_1", 16);
        return bank;
    };
    auto ram_bank0 = make_dram_bank(37);  // U37-U45
    auto ram_bank1 = make_dram_bank(53);  // U53-U61
    auto ram_bank2 = make_dram_bank(69);  // U69-U77
    auto ram_bank3 = make_dram_bank(85);  // U85-U93

    // Wire each DRAM bank: shared MA/WE, per-bank RAS + CAS, per-chip data.
    auto wire_dram_bank = [&](std::vector<Socket>& bank, int bank_idx) {
        for (int chip = 0; chip < 9; ++chip) {
            auto& s = bank[chip];
            // 4164 address pins -> MA bus
            s.wire(5, dram_ma0);   // A0
            s.wire(7, dram_ma1);   // A1
            s.wire(6, dram_ma2);   // A2
            s.wire(12, dram_ma3);  // A3
            s.wire(11, dram_ma4);  // A4
            s.wire(10, dram_ma5);  // A5
            s.wire(13, dram_ma6);  // A6
            s.wire(9, dram_ma7);   // A7
            // Control
            s.wire(3, dram_we);    // ~WE
            s.wire(4, *ras_arr[bank_idx]);   // ~RAS (per-bank, from U49)
            s.wire(15, *dram_cas_arr[bank_idx]);  // ~CAS (per-bank, from U47)
            s.wire(8, vcc);        // VCC
            s.wire(16, gnd);       // GND
            // Data: chip 0 = parity, chips 1-8 = MD0-MD7
            if (chip == 0) {
                s.wire(2, mdp);    // DIN (parity)
                s.wire(14, mdp);   // DOUT (parity)
            } else {
                s.wire(2, *md_arr[chip - 1]);   // DIN
                s.wire(14, *md_arr[chip - 1]);  // DOUT
            }
        }
    };
    wire_dram_bank(ram_bank0, 0);
    wire_dram_bank(ram_bank1, 1);
    wire_dram_bank(ram_bank2, 2);
    wire_dram_bank(ram_bank3, 3);

    IC_DRAM_256K dram;
    dram.install(ram_bank0, ram_bank1, ram_bank2, ram_bank3);

    // U62: 74S158 DRAM Address MUX (low nibble: MA0-MA3)
    // SELECT=ADDR_SEL, ~STROBE=GND (always enabled)
    // Low: MA[0:3] = ~{A0,A1,A2,A3}  High: MA[0:3] = ~{A8,A9,A10,A11}
    Socket mux_lo{"U62", "74S158", 16};
    mux_lo.wire(1, addr_sel);          // SELECT
    mux_lo.wire(2, xa[0]);             // I0a = A0
    mux_lo.wire(3, xa[8]);             // I1a = A8
    mux_lo.wire(4, dram_ma0);          // Ya = MA0
    mux_lo.wire(5, xa[1]);             // I0b = A1
    mux_lo.wire(6, xa[9]);             // I1b = A9
    mux_lo.wire(7, dram_ma1);          // Yb = MA1
    mux_lo.wire(8, gnd);               // GND
    mux_lo.wire(9, dram_ma2);          // Yc = MA2
    mux_lo.wire(10, xa[10]);           // I1c = A10
    mux_lo.wire(11, xa[2]);            // I0c = A2
    mux_lo.wire(12, dram_ma3);         // Yd = MA3
    mux_lo.wire(13, xa[11]);           // I1d = A11
    mux_lo.wire(14, xa[3]);            // I0d = A3
    mux_lo.wire(15, gnd);              // ~STROBE = GND (always enabled)
    mux_lo.wire(16, vcc);              // VCC
    auto* mux_lo_ic = mux_lo.emplace<IC_74S158>();

    // U79: 74S158 DRAM Address MUX (high nibble: MA4-MA7)
    Socket mux_hi{"U79", "74S158", 16};
    mux_hi.wire(1, addr_sel);          // SELECT
    mux_hi.wire(2, xa[4]);             // I0a = A4
    mux_hi.wire(3, xa[12]);            // I1a = A12
    mux_hi.wire(4, dram_ma4);          // Ya = MA4
    mux_hi.wire(5, xa[5]);             // I0b = A5
    mux_hi.wire(6, xa[13]);            // I1b = A13
    mux_hi.wire(7, dram_ma5);          // Yb = MA5
    mux_hi.wire(8, gnd);               // GND
    mux_hi.wire(9, dram_ma6);          // Yc = MA6
    mux_hi.wire(10, xa[14]);           // I1c = A14
    mux_hi.wire(11, xa[6]);            // I0c = A6
    mux_hi.wire(12, dram_ma7);         // Yd = MA7
    mux_hi.wire(13, xa[15]);           // I1d = A15
    mux_hi.wire(14, xa[7]);            // I0d = A7
    mux_hi.wire(15, gnd);              // ~STROBE = GND (always enabled)
    mux_hi.wire(16, vcc);              // VCC
    auto* mux_hi_ic = mux_hi.emplace<IC_74S158>();

    // U81: 74S00 NAND -- RAS/CAS generation + refresh gating.
    // Gate 1: DACK0 NAND RAS -> ~REFRSH_GATE
    // Gate 2: ~MEMR NAND ~MEMW -> RAS (fires when either memory cmd active)
    // Gate 3: N-000258 NAND N-000253 -> ~CAS (TD1 delayed RAS inputs)
    // Gate 4: unconnected (parity/channel check, N.P. signals)
    Socket nand81_socket{"U81", "74S00", 14};
    nand81_socket.wire(1, gnd);            // A1 = DACK0 (Low = no DMA)
    nand81_socket.wire(2, ras);            // B1 = RAS
    nand81_socket.wire(3, refrsh_gate);    // Y1 = ~REFRSH_GATE
    nand81_socket.wire(4, memr);           // A2 = ~MEMR
    nand81_socket.wire(5, memw);           // B2 = ~MEMW
    nand81_socket.wire(6, ras);            // Y2 = RAS
    nand81_socket.wire(7, gnd);
    nand81_socket.wire(8, cas);            // Y3 = ~CAS
    // Pins 9,10 not wired -- gate 3 uses virtual TD1 (delayed RAS) internally.
    nand81_socket.wire(14, vcc);
    auto* nand81_ic = nand81_socket.emplace<IC_74S00_U81>();
    nand81_ic->connect_addr_sel(addr_sel);

    // U48: 74S138 RAM Address Range Select
    // A=GND, B=GND, C=A18, ~G2A=GND, ~G2B=A19, G1=VCC (no DMA).
    // ~Y0 = ~RAM_ADDR_SEL: active for addresses 0x00000-0x3FFFF.
    Socket ram_range{"U48", "74S138", 16};
    ram_range.wire(1, gnd);                // A = 0
    ram_range.wire(2, gnd);                // B = 0
    ram_range.wire(3, xa[18]);             // C = A18
    ram_range.wire(4, gnd);                // ~G2A = GND (always enabled)
    ram_range.wire(5, xa[19]);             // ~G2B = A19 (Low for < 512K)
    ram_range.wire(6, vcc);                // G1 = VCC (~DACK_0_BRD, no DMA)
    ram_range.wire(8, gnd);
    ram_range.wire(15, ram_addr_sel);      // ~Y0 = ~RAM_ADDR_SEL
    ram_range.wire(16, vcc);
    auto* ram_range_ic = ram_range.emplace<IC_74S138>();

    // U65: 74S138 Per-Bank RAS Decoder
    // Decodes A16/A17 into bank selects, enabled by RAS + ~RAM_ADDR_SEL.
    // C=VCC so select range is 4-7 (outputs ~Y4-~Y7).
    Socket ras_decode{"U65", "74S138", 16};
    ras_decode.wire(1, xa[16]);            // A = A16
    ras_decode.wire(2, xa[17]);            // B = A17
    ras_decode.wire(3, vcc);               // C = VCC (select 4-7)
    ras_decode.wire(4, gnd);               // ~G2A = DACK0 (Low = no DMA)
    ras_decode.wire(5, ram_addr_sel);      // ~G2B = ~RAM_ADDR_SEL
    ras_decode.wire(6, ras);               // G1 = RAS (active high)
    ras_decode.wire(7, bank_sel_y7);       // ~Y7 = N-000252 (bank 3)
    ras_decode.wire(8, gnd);
    ras_decode.wire(9, bank_sel_y6);       // ~Y6 = N-000255 (bank 2)
    ras_decode.wire(10, bank_sel_y5);      // ~Y5 = N-000251 (bank 1)
    ras_decode.wire(11, bank_sel_y4);      // ~Y4 = N-000256 (bank 0)
    ras_decode.wire(16, vcc);
    auto* ras_dec = ras_decode.emplace<IC_74S138>();

    // U49: 74S08 Per-Bank RAS Gate
    // ANDs bank selects from U65 with ~REFRSH_GATE from U81.
    // Gate 3: N-000256 AND ~REFRSH_GATE -> ~RAS0
    // Gate 4: N-000251 AND ~REFRSH_GATE -> ~RAS1
    // Gate 1: N-000255 AND ~REFRSH_GATE -> ~RAS2
    // Gate 2: N-000252 AND ~REFRSH_GATE -> ~RAS3
    Socket ras_gate{"U49", "74S08", 14};
    ras_gate.wire(1, bank_sel_y6);         // A1 = N-000255
    ras_gate.wire(2, refrsh_gate);         // B1 = ~REFRSH_GATE
    ras_gate.wire(3, ras2);                // Y1 = ~RAS2
    ras_gate.wire(4, bank_sel_y7);         // A2 = N-000252
    ras_gate.wire(5, refrsh_gate);         // B2 = ~REFRSH_GATE
    ras_gate.wire(6, ras3);                // Y2 = ~RAS3
    ras_gate.wire(7, gnd);
    ras_gate.wire(8, ras0);                // Y3 = ~RAS0
    ras_gate.wire(9, bank_sel_y4);         // A3 = N-000256
    ras_gate.wire(10, refrsh_gate);        // B3 = ~REFRSH_GATE
    ras_gate.wire(11, ras1);               // Y4 = ~RAS1
    ras_gate.wire(12, bank_sel_y5);        // A4 = N-000251
    ras_gate.wire(13, refrsh_gate);        // B4 = ~REFRSH_GATE
    ras_gate.wire(14, vcc);
    auto* ras_gate_ic = ras_gate.emplace<IC_74S08>();

    // U47: 74S138 Per-Bank CAS Decoder
    // Decodes A16/A17 into per-bank ~CAS0-3, enabled by ~CAS + ~RAM_ADDR_SEL.
    Socket cas_decode{"U47", "74S138", 16};
    cas_decode.wire(1, xa[16]);            // A = A16
    cas_decode.wire(2, xa[17]);            // B = A17
    cas_decode.wire(3, gnd);               // C = GND (select 0-3)
    cas_decode.wire(4, ram_addr_sel);      // ~G2A = ~RAM_ADDR_SEL
    cas_decode.wire(5, cas);               // ~G2B = ~CAS
    cas_decode.wire(6, vcc);               // G1 = VCC (~DACK_0_BRD, no DMA)
    cas_decode.wire(8, gnd);
    cas_decode.wire(12, dram_cas3);        // ~Y3 = ~CAS3
    cas_decode.wire(13, dram_cas2);        // ~Y2 = ~CAS2
    cas_decode.wire(14, dram_cas1);        // ~Y1 = ~CAS1
    cas_decode.wire(15, dram_cas0);        // ~Y0 = ~CAS0
    cas_decode.wire(16, vcc);
    auto* cas_dec = cas_decode.emplace<IC_74S138>();

    // BusGlue: reactive address decode + memory
    Signal* xa_ptrs[20];
    Signal* d_ptrs[8];
    for (int i = 0; i < 20; ++i) xa_ptrs[i] = &xa[i];
    for (int i = 0; i < 8; ++i)  d_ptrs[i] = d_arr[i];

    BusGlue bus;
    bus.init(xa_ptrs, d_ptrs, s0, s1, s2, clk);
    bus.connect_dram_we(dram_we);
    for (int i = 0; i < 8; ++i) {
        bus.pic_ir[i] = irq_arr[i];
        bus.declare_output(irq_arr[i]->pin());
    }

    // Scheduler: commits signals, evals inline ICs, runs fiber components.
    // The 8284A calls scheduler.evaluate(self) at each CLK edge from its spin loop.
    // All fiber components run cooperatively on the 8284A's thread.
    Scheduler scheduler;
    Signal::set_scheduler(&scheduler);
    scheduler.register_callback(xcvr);
    scheduler.register_callback(mem_xcvr);
    scheduler.register_callback(latch_lo_ic);
    scheduler.register_callback(latch_mid_ic);
    scheduler.register_callback(latch_hi_ic);
    scheduler.register_callback(io_dec);
    scheduler.register_callback(nand_ic);
    scheduler.register_callback(rom_dec);
    scheduler.register_callback(rom_ic);
    scheduler.register_callback(mux_lo_ic);
    scheduler.register_callback(mux_hi_ic);
    scheduler.register_callback(nand81_ic);
    scheduler.register_callback(ram_range_ic);
    scheduler.register_callback(ras_dec);
    scheduler.register_callback(ras_gate_ic);
    scheduler.register_callback(cas_dec);
    scheduler.register_callback(&dram);
    scheduler.register_callback(bc);
    scheduler.register_callback(pic);
    scheduler.register_callback(&bus);
    // Register fiber components (everything except the 8284A clock).
    scheduler.register_fiber(cpu);
    // Register threaded components for visualization only.
    scheduler.register_visual(clk_gen);
    // Resolve callback dependency graph (DRAM outputs -> BusGlue inputs).
    // Must be called after all register_*() calls so dump_dot sees everything.
    scheduler.resolve();
    // Throwaway: measure fiber dispatch overhead with a no-op fiber.
    //NoopFiber noop_fiber;
    //noop_fiber.power_on();
    //scheduler.register_fiber(&noop_fiber);
    clk_gen->set_scheduler(&scheduler);
    cpu->set_scheduler(&scheduler);

    // --- Run tests (power cycle between each) ---
    int passed = 0, failed = 0;

    for (auto& tc : tests) {
        spdlog::info("--- {} ---", tc.name);

        // Reset I/O space, DRAM, and BusGlue state
        std::memset(bus.io.get(), 0xFF, 1 << 16);
        std::memset(dram.data(), 0xF4, IC_DRAM_256K::size());
        bus.reset();

        // Load binary into DRAM at 0100:0100 (physical 0x01100)
        std::string path = std::string(ASM_TEST_DIR) + "/" + tc.bin_file;
        if (!load_bin(path, dram.data(), 0x1100, IC_DRAM_256K::size())) { ++failed; continue; }

        // Verify load
        spdlog::trace("  dram[01100..01107] = {:02X} {:02X} {:02X} {:02X} {:02X} {:02X} {:02X} {:02X}",
            dram.data()[0x1100], dram.data()[0x1101], dram.data()[0x1102], dram.data()[0x1103],
            dram.data()[0x1104], dram.data()[0x1105], dram.data()[0x1106], dram.data()[0x1107]);

        // Seat all ICs (threads start, block on wait_mailbox).
        cpu->clear_halt();
#ifdef BENCH_PIN_VALIDATION
        SignalPool::enable_validation();
#endif
        pic->power_on();
        bc->power_on();
        xcvr->power_on();
        mem_xcvr->power_on();
        io_dec->power_on();
        nand_ic->power_on();
        rom_dec->power_on();
        rom_ic->power_on();
        dram.power_on();
        mux_lo_ic->power_on();
        mux_hi_ic->power_on();
        nand81_ic->power_on();
        ram_range_ic->power_on();
        ras_dec->power_on();
        ras_gate_ic->power_on();
        cas_dec->power_on();
        latch_lo_ic->power_on();
        latch_mid_ic->power_on();
        latch_hi_ic->power_on();
        bus.power_on();
        clk_gen->power_on();
        cpu->power_on();
        spdlog::debug("All ICs seated, pending={}", Signal::pending_count.load());

        // Flip the switch (PSU drives GND, VCC, S0-S2, AEN, RES on clock thread).
        clk_gen->psu_power_on();

        // Wait for CPU to halt, with 10s safety timeout.
        {
            auto deadline = std::chrono::steady_clock::now() + std::chrono::seconds(10);
            while (!cpu->halted() && std::chrono::steady_clock::now() < deadline)
                std::this_thread::sleep_for(std::chrono::microseconds(100));
            if (!cpu->halted())
                spdlog::warn("  timeout -- CPU did not halt within 10s");
        }

        // Power off (PSU drops VCC on clock thread, 8284A stops).
        clk_gen->psu_power_off();
        clk_gen->power_off();   // stop clock first -- joins 8284A thread
        cpu->power_off();       // then delete fibers
        bc->power_off();
        pic->power_off();
        bus.power_off();
        dram.power_off();
        mux_lo_ic->power_off();
        mux_hi_ic->power_off();
        nand81_ic->power_off();
        ram_range_ic->power_off();
        ras_dec->power_off();
        ras_gate_ic->power_off();
        cas_dec->power_off();
        rom_ic->power_off();
        xcvr->power_off();
        mem_xcvr->power_off();
        io_dec->power_off();
        nand_ic->power_off();
        rom_dec->power_off();
        latch_lo_ic->power_off();
        latch_mid_ic->power_off();
        latch_hi_ic->power_off();

        // Power loss: every trace on the board discharges.
        for (auto* sig : all_traces)
            sig->reset();

        // Check results -- read from DRAM through 74S158 address translation.
        bool pass = true;
        const uint8_t* ram = dram.data();
        for (auto& e : tc.expects) {
            uint16_t actual = ram[dram_xlat(e.addr)] | (ram[dram_xlat(e.addr + 1)] << 8);
            if (actual != e.value) {
                spdlog::error("  FAIL {}: [0x{:04X}] = 0x{:04X} (expected 0x{:04X})",
                    e.label, e.addr, actual, e.value);
                pass = false;
            } else {
                spdlog::info("  ok   {}: [0x{:04X}] = 0x{:04X}",
                    e.label, e.addr, actual);
            }
        }
        if (pass) ++passed; else ++failed;
    }

    spdlog::info("=== Results: {} passed, {} failed ===", passed, failed);

#define RUN_BENCHMARK

#if defined(RUN_BENCHMARK)
    // --- Benchmark: 64-bit increment loop, timed by NMI ---
    constexpr int BENCH_SECONDS = 5;
    spdlog::info("--- Benchmark: 64-bit increment ({} seconds) ---", BENCH_SECONDS);
    {
        std::memset(bus.io.get(), 0xFF, 1 << 16);
        std::memset(dram.data(), 0xF4, IC_DRAM_256K::size());
        bus.reset();

        std::string path = std::string(ASM_TEST_DIR) + "/test_bench64.bin";
        if (!load_bin(path, dram.data(), 0x1100, IC_DRAM_256K::size())) {
            spdlog::error("  benchmark skipped -- cannot load binary");
        }
        else {
            cpu->clear_halt();
#ifdef BENCH_PIN_VALIDATION
            SignalPool::enable_validation();
#endif
            pic->power_on();
            bc->power_on();
            xcvr->power_on();
            mem_xcvr->power_on();
            io_dec->power_on();
            nand_ic->power_on();
            rom_dec->power_on();
            rom_ic->power_on();
            dram.power_on();
            mux_lo_ic->power_on();
            mux_hi_ic->power_on();
            nand81_ic->power_on();
            ram_range_ic->power_on();
            ras_dec->power_on();
            ras_gate_ic->power_on();
            cas_dec->power_on();
            latch_lo_ic->power_on();
            latch_mid_ic->power_on();
            latch_hi_ic->power_on();
            bus.power_on();
            clk_gen->power_on();
            cpu->power_on();

            clk_gen->psu_power_on();

            // Let it run for BENCH_SECONDS, then fire NMI.
            auto start = std::chrono::steady_clock::now();
            std::this_thread::sleep_for(std::chrono::seconds(BENCH_SECONDS));
            clk_gen->psu_nmi_raise();

            // Wait for CPU to halt (NMI handler does HLT).
            auto deadline = std::chrono::steady_clock::now() + std::chrono::seconds(5);
            while (!cpu->halted() && std::chrono::steady_clock::now() < deadline)
                std::this_thread::sleep_for(std::chrono::microseconds(100));
            auto end = std::chrono::steady_clock::now();

            double elapsed = std::chrono::duration<double>(end - start).count();

            if (!cpu->halted())
                spdlog::warn("  benchmark timeout -- CPU did not halt");

            // Power off.
            clk_gen->psu_nmi_lower();
            clk_gen->psu_power_off();
            // Wait for 8284A to see VCC drop and stop.
            clk_gen->power_off();
            cpu->power_off();
            bc->power_off();
            pic->power_off();
            bus.power_off();
            dram.power_off();
            mux_lo_ic->power_off();
            mux_hi_ic->power_off();
            nand81_ic->power_off();
            ram_range_ic->power_off();
            ras_dec->power_off();
            ras_gate_ic->power_off();
            cas_dec->power_off();
            rom_ic->power_off();
            xcvr->power_off();
            mem_xcvr->power_off();
            io_dec->power_off();
            nand_ic->power_off();
            rom_dec->power_off();
            latch_lo_ic->power_off();
            latch_mid_ic->power_off();
            latch_hi_ic->power_off();

            // Read 64-bit counter from DRAM (through 74S158 translation).
            uint64_t count = 0;
            for (int i = 0; i < 8; ++i)
                count |= (uint64_t)dram.data()[dram_xlat(0x0500 + i)] << (i * 8);

            double rate = (elapsed > 0) ? (double)count / elapsed : 0;
            uint64_t cycles = clk_gen->clk_cycles();
            double mhz = (elapsed > 0) ? (double)cycles / elapsed / 1e6 : 0;
            spdlog::info("  count: {} increments in {:.3f}s ({:.0f} inc/s)",
                count, elapsed, rate);
            spdlog::info("  CLK: {} cycles ({:.3f} MHz, target 4.77 MHz)",
                cycles, mhz);

            for (auto* sig : all_traces)
                sig->reset();
        }
    }
#endif

    #define DUMP_PERMUTATIONS

#if defined(DUMP_PERMUTATIONS)
    spdlog::info("--- Dumping encountered DAG permutations as SVG ---");
    scheduler.dump_permutation_svgs();
#endif


    return failed > 0 ? 1 : 0;
}
